### ISSUE TITLE
Implement "Laser Weapon"

### ISSUE THREAD

**Issue by fireball1983** [cs361fall2018/project-team40#112]
Let's you attack a submarine and pierce through ships on top of each other, unlocks after the first enemy ship is destroyed.

**Comment by fireball1983** [comment]
@montymxb To poke on the whole "repeating attacks portion" when we activate the laser, I just realized the part about removing the "Result Check: " portion in AttackUtility might not work since I think that's how we stop the user from just repeatedly attacking 1 ship square to decrement its health. I'm not sure really since we'd have to erase misses anyways since the ships gotta move.

**Comment by montymxb** [comment]
The ships should be able to tell if there's a repeat attack, so that attempting to attack a space again would just fail. We could indicate which space was attacked in addition to health, and put it an array to avoid repeated damage taken on that same location. This would have to be preserved across the ships moving, so we wouldn't just add coordinates, would have to be more basic layout of position 1,2,3, etc. One end of the ship (probably that closest to the captain's quarters) would always be 1, and then counts until it hits the end. If the ship moves and is attacked on a new space, but the position on the ship was already hit then it shouldn't register as any extra damage.

**Comment by fireball1983** [comment]
Closed, I think Ben finished this one.
