### ISSUE TITLE
Refactor squareOccupied in board

### ISSUE THREAD

**Issue by horinezachary** [cs361fall2018/project-team40#25]
squareOccupied is currently not stateless.

**Comment by montymxb** [comment]
**occupiedSquares** is actually ok. The server receives a JSON object on each request that sets everything up. When the server makes a change this is done to whatever objects, but all underneath the main game object. The response it returns is actually the whole underlying structure of the game object being returned as JSON. This kind of ping-pong setup is how the server remains stateless, since in-between requests it isn't persisting anything, it just sets up for each call based on what's returned in the JSON.

A really good way to check this is by opening up the inspector in your browser and watching the network requests. You'll be able to see that it's just JSON being sent, and JSON being returned, and it mirrors the structure of what we have in terms of objects & their properties.

**Comment by montymxb** [comment]
Closed by merging #34
