### ISSUE TITLE
Finish "get occupied squares"

### ISSUE THREAD

**Issue by fireball1983** [cs361fall2018/project-team40#6]
I'm reading up on this, it looks like this might be how we keep track of the number of squares the ship takes up, regardless, the ship class needs to extend the square class if it wants to use it.

**Comment by montymxb** [comment]
Looks like the **occupiedSquares** property just holds the spaces that particular ship occupies. The call to place being [in Game.java on line 19](https://github.com/cs361fall2018/project-team40/blob/master/src/main/java/cs361/battleships/models/Game.java#L19), and the logic for adding the ship to the board (and setting up it's squares) being in [Board.java on line 18](https://github.com/cs361fall2018/project-team40/blob/master/src/main/java/cs361/battleships/models/Board.java#L18...L21).

Probably don't need to extend the squares class, since all we need it is for the occupied spaces. If anything we may want to consider creating other ship subclasses that extend 'Ship', and I imagine we might be asked to do that later in another sprint.

**Comment by horinezachary** [comment]
I covered this in the placement of ships. The ship, when initialized, sets its size, and all of the placement functions use this to determine how many squares to assign to the ship. it then passes these squares to the ship in the form of a list. These squares also keep track of whether or not they are occupied or not to make checking for pre-occupied squares more efficient.
