### ISSUE TITLE
Basic individual requirements

### ISSUE THREAD

**Issue by fireball1983** [cs361fall2018/project-team40#90]
Assigned to at least 1 issue
- [x] Ben
- [x] Michael
- [x] Zach
- [x] Jhonatan

Reviewed 1 PR
- [x] Ben
- [x] Michael
- [x] Zach
- [x] Jhonatan

Merged 1 PR
- [x] Ben
- [x] Michael
- [x] Zach
- [x] Jhonatan

Pull request is tested
- The feature you make needs test cases, worth ~10 points.
- [x] Ben
- [x] Michael
- [x] Zach
- [x] Jhonatan

**Comment by montymxb** [comment]
Double checked the instructions, doesn't seem we each had to provide tests as a requirement of our contributions, unless it was adding Java specific code. So @johnnybecerra should be good here since he made contributions related to the JS, graphics design and UI development portions of this project.
